# 16x16-Pixel-Icons für die Axiom-Werkzeuge (ASCII-Art, ein Zeichen = ein Pixel).
PALETTE = {
    ".": None,
    "k": (27, 27, 47),  # Umriss
    "w": (255, 255, 255),
    "b": (160, 104, 52),  # Griff hell
    "B": (100, 62, 28),  # Griff dunkel
    "p": (190, 90, 240),  # Lila
    "P": (110, 40, 160),
    "c": (90, 220, 240),  # Cyan
    "C": (30, 140, 170),
    "y": (255, 220, 70),  # Gelb
    "Y": (200, 150, 0),
    "g": (200, 200, 215),  # Grau/Metall
    "G": (110, 110, 125),
    "r": (235, 80, 80),  # Rot
    "R": (150, 30, 30),
    "e": (100, 200, 80),  # Grün
    "E": (45, 120, 40),
    "o": (245, 160, 60),  # Orange
    "O": (170, 95, 20),
    "u": (80, 130, 235),  # Blau
    "U": (35, 65, 160),
    "d": (140, 100, 65),  # Erde
    "D": (95, 65, 40),
    "s": (150, 150, 150),  # Stein
    "S": (100, 100, 100),
}

ICONS = {
    "menu": [
        "................",
        ".....kkkkkk.....",
        "...kkppppppkk...",
        "..kpppppppppPk..",
        "..kppppwwpppPk..",
        ".kppppwppwpppPk.",
        ".kpppwppppwppPk.",
        ".kpppwwwwwwppPk.",
        ".kpppwppppwppPk.",
        ".kpppwppppwpPPk.",
        "..kppppppppPPk..",
        "..kPpppppPPPPk..",
        "...kkPPPPPPkk...",
        ".....kkkkkk.....",
        "......kyyk......",
        ".......kk.......",
    ],
    "box_select": [
        "................",
        ".cc.cc.cc.cc.c..",
        ".c...........c..",
        "................",
        ".c...........c..",
        ".c...........c..",
        "................",
        ".c...........c..",
        ".c......kk...c..",
        ".......kgGk.....",
        ".c....kbGk...c..",
        ".c...kbBk....c..",
        "....kbBk........",
        ".c.kbBk.c.cc.c..",
        "..kbBk..........",
        "..kkk...........",
    ],
    "magic_select": [
        "..........y.....",
        ".........yYy....",
        ".....y.yyyYyyy..",
        "........yYwYy...",
        ".........yYy..y.",
        "........yy.yy...",
        "........y...y...",
        ".......kk.......",
        "......kpPk......",
        ".....kpPk.......",
        "....kbBk........",
        "...kbBk.........",
        "..kbBk..........",
        ".kbBk...........",
        ".kBk............",
        ".kk.............",
    ],
    "brush_select": [
        "................",
        "...........c.c..",
        "..........c.c.c.",
        "...........kkc..",
        "..........kcCkc.",
        ".........kcCCk..",
        "........kgGGk...",
        ".......kgGk.....",
        "......kbBk......",
        ".....kbBk.......",
        "....kbBk........",
        "...kbBk.........",
        "..kbBk..........",
        "..kBk...........",
        "..kk............",
        "................",
    ],
    "builder": [
        "................",
        "....kkkkkkkk....",
        "...kGggggggGk...",
        "...kGgggggggk...",
        "...kGGGGGGGGk...",
        "....kkkbBkkk....",
        ".......bBk......",
        ".......bBk......",
        ".......bBk......",
        ".......bBk......",
        ".......bBk......",
        ".......bBk......",
        ".......bBk......",
        ".......BBk......",
        "........k.......",
        "................",
    ],
    "shape": [
        "................",
        "....kkkk........",
        "..kkuuuukk......",
        ".kuuwuuuuUk.....",
        ".kuwuuuuuUk.....",
        "kuuuuuuuuUUk....",
        "kuuuuuuuUUUk....",
        "kuuuuuukkkkkkkk.",
        ".kuuuUUkoooooOk.",
        ".kUUUUUkoooooOk.",
        "..kkUUUkoooooOk.",
        "....kkkkoooooOk.",
        ".......kooooOOk.",
        ".......kOOOOOOk.",
        ".......kkkkkkkk.",
        "................",
    ],
    "sculpt": [
        "................",
        "............kk..",
        "...........kgGk.",
        "..........kggGk.",
        ".........kggGk..",
        "........kggGk...",
        ".......kgGGk....",
        "......kkGkk.....",
        ".....kbBk.......",
        "....kbBk........",
        "...kbBk.........",
        "..kbBk..........",
        ".kbBk...ddd.....",
        ".kBk..ddddddd...",
        ".kk.ddddDDdddd..",
        "...dddDDDDDDddd.",
    ],
    "painter": [
        "................",
        "...........kk...",
        "..........krrk..",
        ".........krrRk..",
        "........krrRk...",
        "........kGGk....",
        ".......kgGk.....",
        "......kbBk......",
        ".....kbBk.......",
        "....kbBk........",
        "...kbBk.........",
        "..kbBk..........",
        "..kBk.......r...",
        "..kk......rrRr..",
        "..........rRRr..",
        "...........rr...",
    ],
    "terrain": [
        "................",
        "................",
        "......ee........",
        ".....eEEe.......",
        "....eEddEe......",
        "...eEddddEe..ee.",
        "..eEddddddEeeEEe",
        ".eEddddDDddddddE",
        "eEdddDDDDDDddddd",
        "dddDDDDsDDDDDddd",
        "dDDDDssssDDDDDDd",
        "DDDsssssssDDDDDD",
        "DsssssSSsssssDDD",
        "sssSSSSSSSSsssss",
        "ssSSSSSSSSSSSSss",
        "SSSSSSSSSSSSSSSS",
    ],
    "extrude": [
        "................",
        ".......kk.......",
        "......kyyk......",
        ".....kyyyyk.....",
        "....kyyyyyyk....",
        "....kkkyykkk....",
        "......kyyk......",
        "..kkkkkyykkkkk..",
        "..keeeeeeeeeek..",
        "..kEEEEEEEEEEk..",
        "..kddddddddddk..",
        "..kdDddddDdddk..",
        "..kddddDdddddk..",
        "..kDdddddddDdk..",
        "..kkkkkkkkkkkk..",
        "................",
    ],
    "path": [
        "................",
        ".............kk.",
        "............kyyk",
        "............kyyk",
        "...........o.kk.",
        "..........o.....",
        ".........o......",
        "........o.......",
        ".......o........",
        "......o.........",
        ".....o..........",
        "....o...........",
        ".kk.............",
        "kyyk............",
        "kyyk............",
        ".kk.............",
    ],
    "text": [
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kccccccccccccCk",
        ".kccccccccccccCk",
        ".kCCCCkccCCCCCCk",
        "..kkkkkcckkkkkk.",
        "......kccCk.....",
        "......kccCk.....",
        "......kccCk.....",
        "......kccCk.....",
        "......kccCk.....",
        "......kccCk.....",
        "......kccCk.....",
        ".....kkcCCkk....",
        "......kkkkk.....",
        "................",
    ],
    "ruler": [
        "................",
        "..........kkk...",
        ".........kyyYk..",
        "........kyyyYk..",
        ".......kykyYk...",
        "......kyyyYk....",
        ".....kykyYk.....",
        "....kyyyYk......",
        "...kykyYk.......",
        "..kyyyYk........",
        ".kykyYk.........",
        ".kyyYk..........",
        ".kYYk...........",
        ".kkk............",
        "................",
        "................",
    ],
    "tinker": [
        "................",
        "..........kkk...",
        ".........kgk.k..",
        "........kgGk....",
        "........kgGk.kk.",
        "........kggGkgk.",
        ".......kgGGggGk.",
        "......kgGkkkkk..",
        ".....kgGk.......",
        "....kgGk........",
        "...kgGk.........",
        "..kgGk..........",
        ".kgGk...........",
        ".kGk............",
        ".kk.............",
        "................",
    ],
    "bulldozer": [
        "................",
        "....kkkkkkk.....",
        "...kyyyyyyYk....",
        "..kyYkkkkkyYk...",
        "..kYk.kbk.kYk...",
        "..kk..kbk..kk...",
        "......kbBk......",
        "......kbBk......",
        "......kbBk......",
        "......kbBk......",
        "......kbBk......",
        "......kbBk......",
        "......kbBk......",
        "......kBBk......",
        ".......kk.......",
        "................",
    ],
    "undo": [
        "................",
        "................",
        ".....kkkkk......",
        "...kkcccccCk....",
        "..kcCkkkkkcCk...",
        ".kcCk.....kcCk..",
        "kkcCkkk....kcCk.",
        "kcccccCk...kcCk.",
        ".kcccCk....kcCk.",
        "..kcCk.....kcCk.",
        "...kk.....kcCk..",
        ".........kcCk...",
        "......kkkcCk....",
        "......kcCCk.....",
        "......kkkk......",
        "................",
    ],
}
